-- Add data to temporary table
CREATE TEMPORARY TABLE SPLITTRANSACTIONS_V1_TEMP AS SELECT * FROM SPLITTRANSACTIONS_V1;

-- Drop old table
DROP TABLE SPLITTRANSACTIONS_V1;

-- Create new table and indexes
CREATE TABLE SPLITTRANSACTIONS_V1(
SPLITTRANSID integer primary key
, ACCOUNTID integer NOT NULL
, TRANSID integer NOT NULL
, CATEGID integer
, SUBCATEGID integer
, SPLITTRANSAMOUNT numeric
, NOTES TEXT
);
CREATE INDEX IDX_SPLITTRANSACTIONS_ACCOUNTID ON SPLITTRANSACTIONS_V1(ACCOUNTID);
CREATE INDEX IDX_SPLITTRANSACTIONS_TRANSID ON SPLITTRANSACTIONS_V1(TRANSID);

-- Reinsert data
INSERT INTO SPLITTRANSACTIONS_V1
   SELECT SPLITTRANSID, ACCOUNTID, S.TRANSID, S.CATEGID, S.SUBCATEGID, SPLITTRANSAMOUNT, ''
   FROM SPLITTRANSACTIONS_V1_TEMP S INNER JOIN CHECKINGACCOUNT_V1 T ON S.TRANSID = T.TRANSID;