-- SPLITTRANSACTIONS_V1
CREATE TEMPORARY TABLE SPLITTRANSACTIONS_V1_TEMP AS SELECT * FROM SPLITTRANSACTIONS_V1;

DROP TABLE SPLITTRANSACTIONS_V1;

CREATE TABLE SPLITTRANSACTIONS_V1(
SPLITTRANSID integer primary key
, ACCOUNTID integer NOT NULL
, TRANSID integer NOT NULL
, CATEGID integer
, SUBCATEGID integer
, SPLITTRANSAMOUNT numeric
, NOTES TEXT
);
CREATE INDEX IDX_SPLITTRANSACTIONS_ACCOUNTID ON SPLITTRANSACTIONS_V1(ACCOUNTID);
CREATE INDEX IDX_SPLITTRANSACTIONS_TRANSID ON SPLITTRANSACTIONS_V1(TRANSID);

INSERT INTO SPLITTRANSACTIONS_V1
   SELECT SPLITTRANSID, ACCOUNTID, S.TRANSID, S.CATEGID, S.SUBCATEGID, SPLITTRANSAMOUNT, ''
   FROM SPLITTRANSACTIONS_V1_TEMP S INNER JOIN CHECKINGACCOUNT_V1 T ON S.TRANSID = T.TRANSID;

DROP TABLE SPLITTRANSACTIONS_V1_TEMP;


-- BUDGETSPLITTRANSACTIONS_V1 
CREATE TEMPORARY TABLE BUDGETSPLITTRANSACTIONS_V1_TEMP AS SELECT * FROM BUDGETSPLITTRANSACTIONS_V1;

DROP TABLE BUDGETSPLITTRANSACTIONS_V1;

CREATE TABLE BUDGETSPLITTRANSACTIONS_V1(
SPLITTRANSID integer primary key
, ACCOUNTID integer NOT NULL
, TRANSID integer NOT NULL
, CATEGID integer
, SUBCATEGID integer
, SPLITTRANSAMOUNT numeric
, NOTES TEXT
);
CREATE INDEX IDX_BUDGETSPLITTRANSACTIONS_ACCOUNTID ON BUDGETSPLITTRANSACTIONS_V1(ACCOUNTID);
CREATE INDEX IDX_BUDGETSPLITTRANSACTIONS_TRANSID ON BUDGETSPLITTRANSACTIONS_V1(TRANSID);

INSERT INTO BUDGETSPLITTRANSACTIONS_V1
   SELECT SPLITTRANSID, ACCOUNTID, S.TRANSID, S.CATEGID, S.SUBCATEGID, SPLITTRANSAMOUNT, ''
   FROM BUDGETSPLITTRANSACTIONS_V1_TEMP S INNER JOIN BILLSDEPOSITS_V1 BD ON S.TRANSID = BD.BDID;

DROP TABLE BUDGETSPLITTRANSACTIONS_V1_TEMP;