-- remove BASECONVRATE

CREATE TABLE CURRENCYFORMATS_NEW(
CURRENCYID integer primary key
, CURRENCYNAME TEXT COLLATE NOCASE NOT NULL
, PFX_SYMBOL TEXT
, SFX_SYMBOL TEXT
, DECIMAL_POINT TEXT
, GROUP_SEPARATOR TEXT
, SCALE integer
, CURRENCY_SYMBOL TEXT COLLATE NOCASE NOT NULL UNIQUE
, CURRENCY_TYPE TEXT /* Fiat, Crypto */
, HISTORIC integer DEFAULT 0 /* 1 if no longer official */
);

INSERT INTO CURRENCYFORMATS_NEW SELECT
CURRENCYID
, CURRENCYNAME
, PFX_SYMBOL
, SFX_SYMBOL
, DECIMAL_POINT
, GROUP_SEPARATOR
, SCALE
, CURRENCY_SYMBOL
, CURRENCY_TYPE
, HISTORIC
FROM CURRENCYFORMATS;

DROP INDEX IDX_CURRENCYFORMATS_SYMBOL;
DROP TABLE CURRENCYFORMATS;
ALTER TABLE CURRENCYFORMATS_NEW RENAME TO CURRENCYFORMATS;
CREATE INDEX IDX_CURRENCYFORMATS_SYMBOL ON CURRENCYFORMATS(CURRENCY_SYMBOL);

PRAGMA user_version = 12;