-- DB Tidy, redundant views
DROP VIEW IF EXISTS alldata;
DROP VIEW IF EXISTS alldatax;
DROP VIEW IF EXISTS budget;

-- DB Tidy, fix corrupt indices
REINDEX;

-- Nested Categories
-- https://github.com/moneymanagerex/moneymanagerex/issues/1477
UPDATE CATEGORY_V1 
SET CATEGNAME = CATEGNAME || '.' || CATEGID 
WHERE CATEGID IN 
    (
    SELECT CATEGID 
    FROM CATEGORY_V1 AS C 
    INNER JOIN 
        (
        SELECT CATEGNAME 
        FROM CATEGORY_V1 
        GROUP BY CATEGNAME 
        HAVING COUNT(*) > 1
        ) AS D 
    ON C.CATEGNAME = D.CATEGNAME
    );
	
UPDATE SUBCATEGORY_V1 
SET SUBCATEGNAME = SUBCATEGNAME || '.' || SUBCATEGID 
WHERE SUBCATEGID IN 
    (
    SELECT SUBCATEGID 
    FROM SUBCATEGORY_V1 AS S 
    INNER JOIN 
        (
        SELECT SUBCATEGNAME, CATEGID 
        FROM SUBCATEGORY_V1 
        GROUP BY SUBCATEGNAME, CATEGID 
        HAVING COUNT(*) > 1
        ) AS D 
    ON S.SUBCATEGNAME = D.SUBCATEGNAME AND S.CATEGID = D.CATEGID
    );

CREATE TABLE CATEGORY_V1_TEMP
( CATEGID INTEGER PRIMARY KEY,
  CATEGNAME TEXT NOT NULL COLLATE NOCASE,
  ACTIVE INTEGER,
  PARENTID INTEGER,
  UNIQUE(CATEGNAME, PARENTID)
);

INSERT INTO CATEGORY_V1_TEMP (CATEGID, CATEGNAME, ACTIVE, PARENTID)
  SELECT CATEGID, CATEGNAME, ACTIVE, '-1'
  FROM CATEGORY_V1;

INSERT INTO CATEGORY_V1_TEMP (CATEGID, CATEGNAME, ACTIVE, PARENTID)
SELECT (SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_TEMP)), 
	SUBCATEGNAME, ACTIVE, CATEGID
FROM SUBCATEGORY_V1; 

UPDATE CHECKINGACCOUNT_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;
UPDATE BILLSDEPOSITS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;
UPDATE BUDGETSPLITTRANSACTIONS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;
UPDATE SPLITTRANSACTIONS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;
UPDATE BUDGETTABLE_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;
UPDATE PAYEE_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1) WHERE SUBCATEGID <> -1;

DROP TABLE CATEGORY_V1;					   
ALTER TABLE CATEGORY_V1_TEMP RENAME TO CATEGORY_V1;
CREATE INDEX IF NOT EXISTS IDX_CATEGORY_CATEGNAME ON CATEGORY_V1(CATEGNAME);
CREATE INDEX IF NOT EXISTS IDX_CATEGORY_CATEGNAME_PARENTID ON CATEGORY_V1(CATEGNAME, PARENTID);																							   

ALTER TABLE BILLSDEPOSITS_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE BUDGETSPLITTRANSACTIONS_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE BUDGETTABLE_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE CHECKINGACCOUNT_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE PAYEE_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE SPLITTRANSACTIONS_V1 DROP COLUMN SUBCATEGID; 

-- DB Tidy, redundant tables
DROP TABLE IF EXISTS ASSETCLASS_V1;
DROP TABLE IF EXISTS ASSETCLASS_STOCK_V1;
DROP TABLE IF EXISTS SUBCATEGORY_V1;
