-- DB Tidy, redundant views
DROP VIEW IF EXISTS alldata;
DROP VIEW IF EXISTS alldatax;
DROP VIEW IF EXISTS budget;

-- Nested Categories
-- https://github.com/moneymanagerex/moneymanagerex/issues/1477
ALTER TABLE CATEGORY_V1 RENAME TO CATEGORY_V1_OLD;
CREATE TABLE CATEGORY_V1
( CATEGID INTEGER PRIMARY KEY,
  CATEGNAME TEXT NOT NULL COLLATE NOCASE,
  ACTIVE INTEGER,
  PARENTID INTEGER,
  UNIQUE(CATEGNAME, PARENTID)
);
CREATE INDEX IF NOT EXISTS IDX_CATEGORY_CATEGNAME_PARENTID ON CATEGORY_V1(CATEGNAME, PARENTID);

INSERT INTO CATEGORY_V1 (CATEGID, CATEGNAME, ACTIVE, PARENTID)
  SELECT CATEGID, CATEGNAME, ACTIVE, '-1'
  FROM CATEGORY_V1_OLD;

INSERT INTO CATEGORY_V1 (CATEGID, CATEGNAME, ACTIVE, PARENTID)
SELECT (SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1)), 
	SUBCATEGNAME, ACTIVE, CATEGID
FROM SUBCATEGORY_V1; 

UPDATE CHECKINGACCOUNT_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;
UPDATE BILLSDEPOSITS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;
UPDATE BUDGETSPLITTRANSACTIONS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;
UPDATE SPLITTRANSACTIONS_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;
UPDATE BUDGETTABLE_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;
UPDATE PAYEE_V1 SET CATEGID = SUBCATEGID + (SELECT MAX(CATEGID) FROM CATEGORY_V1_OLD) WHERE SUBCATEGID <> -1;

DROP TABLE CATEGORY_V1_OLD;
DROP TABLE IF EXISTS SUBCATEGORY_V1;
ALTER TABLE BILLSDEPOSITS_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE BUDGETSPLITTRANSACTIONS_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE BUDGETTABLE_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE CHECKINGACCOUNT_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE PAYEE_V1 DROP COLUMN SUBCATEGID; 
ALTER TABLE SPLITTRANSACTIONS_V1 DROP COLUMN SUBCATEGID; 

-- DB Tidy, redundant tables
DROP TABLE IF EXISTS ASSETCLASS_V1;
DROP TABLE IF EXISTS ASSETCLASS_STOCK_V1;
