UPDATE CURRENCYFORMATS_V1 SET CURRENCY_TYPE = 'Fiat' WHERE CURRENCY_TYPE <> 'Crypto';
UPDATE ATTACHMENT_V1 SET REFTYPE = 'Bank Account' WHERE REFTYPE = 'BankAccount';
UPDATE ATTACHMENT_V1 SET REFTYPE = 'Recurring Transaction' WHERE REFTYPE = 'RecurringTransaction';
PRAGMA user_version = 11;